language:  generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hernandezmdev/react-test -f ./client/dockerfile.dev ./client

script:
  - docker run hernandezmdev/react-test npm test -- --coverage

after_success:
  - docker build -t hernandezmdev/multi-client ./client
  - docker buiild -t hernandezmdev/multi-nginx ./nginx
  - docker buiild -t hernandezmdev/multi-server ./server
  - docker buiild -t hernandezmdev/multi-worker ./worker